In [1]:
# What is numpy?
# Its an external package used to work with arrays (ndarrays)
# Array is a collection of similar elements
#
# Import the numpy package


In [2]:
import numpy as np

In [3]:
# Create a One Dimensional Array

list1 = [1,2,3,4,5,6]

oneDimExample = np.array(list1)


In [4]:
oneDimExample

array([1, 2, 3, 4, 5, 6])

In [5]:
oneDimExample.ndim #Displays the number of dimensions

1

In [6]:
oneDimExample.shape

(6,)

In [7]:
type(oneDimExample)

numpy.ndarray

In [8]:
#Create a two dimensional array

In [9]:
twoDimExample = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [10]:
twoDimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
twoDimExample.ndim

2

In [12]:
twoDimExample.shape

(3, 3)

In [13]:
type(twoDimExample)

numpy.ndarray

In [14]:
# Big difference between Matrix and Array
# =============================================
# 
# You can create Matrix(np.matrix()) and Array(np.array()) using Numpy. 
#
# Array
twoDimArray = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

twoDimMatrix = np.matrix([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [15]:
# Perform Multiplication of the array
#
# Multiplication of an array is element-wise multiplication
#
#   1 2 3      1 2 3       (1*1) (2*2) (3*3)
#   4 5 6   *  4 5 6   =   (4*4) (5*5) (6*6)
#   7 8 9      7 8 9       (7*7) (8*8) (9*9)

resultArray = twoDimArray * twoDimArray
resultArray

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
# Perform Multiplication of the matrix
#
# Refer the link for more details on Matrix Algebra - https://stattrek.com/tutorials/matrix-algebra-tutorial.aspx

resultMatrix = twoDimMatrix * twoDimMatrix
resultMatrix

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [17]:
# Numpy Array Operation
#
# Arithmetic Operations ---> +,-,*,/,%,**


In [18]:
resultAddition = twoDimArray + twoDimArray
resultAddition

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [22]:
resultSub = twoDimArray - twoDimArray
resultSub

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
resultMul = twoDimArray * twoDimArray
resultMul

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [24]:
resultDiv = twoDimArray / twoDimArray
resultDiv

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
increaseBy2 = twoDimArray ** 2
increaseBy2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [26]:
list(increaseBy2)

[array([1, 4, 9], dtype=int32),
 array([16, 25, 36], dtype=int32),
 array([49, 64, 81], dtype=int32)]

In [28]:
increaseBy2.tolist()

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]