In [2]:
import numpy as np

In [1]:
# arange - Returns evenly spaced values with a given interval
#
# np.arange(start_value, upperbound, stepSize)

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
# Zeros and Ones

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# linspace -- Returns evenly spaced numbers over a specified interval

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [16]:
# Eye --- Identity Array

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.matrix(np.eye(6))

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [20]:
#Random -- To generate random numbers

In [46]:
# Rand returns uniform distribution data
# Uniform Distribution means all your data will be generated within the range of 0,1
np.random.rand(10) 

array([0.3342947 , 0.24366126, 0.3511874 , 0.94708244, 0.8979196 ,
       0.16911521, 0.13841151, 0.39532043, 0.16630645, 0.89508201])

In [47]:
#randn returns Normal Distribution data
# The mean of the values are 0 and Standard Dev of values are 1
np.random.randn(10)

array([-0.46643012,  1.03004655, -1.16277585,  1.08806432, -1.20227655,
        0.4306731 , -1.18084568, -0.35648483,  1.53844972, -0.80143666])

In [56]:
data = np.random.randn(10)
print(np.mean(data))
print(np.std(data))

-0.21049151857703724
1.0987026236797885


In [54]:
#Returns only integer values wiithin the range specified
# randint( startrange, endrange, number of elements)
np.random.randint(1,100,1)

array([21])

In [61]:
np.random.randint(1,100,10)

array([ 9, 18, 31,  7, 16, 18,  2, 97, 87, 44])

In [62]:
# Finding Min,Max,IndexMin,IndexMax


In [63]:
array1 = np.array([4,2,5,2,78,9,900,234,567,2,1])

In [64]:
array1.max() #max value in the array

900

In [65]:
array1.argmax() #index location of the max value

6

In [66]:
array1.min()

1

In [67]:
array1.argmin()

10

In [68]:
np.max(array1)

900

In [69]:
np.min(array1)

1

In [70]:
np.argmax(array1)

6

In [71]:
np.argmin(array1)

10