In [2]:
import numpy as np

In [1]:
# reshape -- Allows you to convert 1d to 2d

In [5]:
data = np.random.randint(1,100,9)

In [6]:
data

array([49,  1, 16, 67, 62, 17, 39, 78, 60])

In [7]:
data.ndim

1

In [13]:
data = data.reshape(3,3)

In [9]:
data.reshape(1,9)

array([[49,  1, 16, 67, 62, 17, 39, 78, 60]])

In [10]:
data.reshape(9,1)

array([[49],
       [ 1],
       [16],
       [67],
       [62],
       [17],
       [39],
       [78],
       [60]])

In [14]:
data

array([[49,  1, 16],
       [67, 62, 17],
       [39, 78, 60]])

In [15]:
# Ravel --- Convert 2d to 1d

In [16]:
data.ndim

2

In [17]:
data

array([[49,  1, 16],
       [67, 62, 17],
       [39, 78, 60]])

In [18]:
data.ravel()

array([49,  1, 16, 67, 62, 17, 39, 78, 60])

In [19]:
data.ravel().ndim

1