In [1]:
import numpy as np

In [2]:
data1 = np.random.randint(1,100,9)

In [3]:
data1

array([86, 73, 70, 54, 26, 27, 96, 70, 48])

In [4]:
data1[6]

96

In [6]:
data1[2:6]

array([70, 54, 26, 27])

In [7]:
data2 = data1.reshape(3,3)

In [8]:
data2 #Row and Column Index starts from 0

array([[86, 73, 70],
       [54, 26, 27],
       [96, 70, 48]])

In [9]:
data2[0,0]

86

In [10]:
data2[2,2]

48

In [11]:
data2[1 , 1:3]

array([26, 27])

In [12]:
data2[0:2 , 1:3]

array([[73, 70],
       [26, 27]])

In [13]:
#     row_index    col_index
# 86   0             0
# 70   0             2
# 96   2             0
# 48   2             2

In [14]:
#Fancy Indexing

data2[[0,0,2,2],[0,2,0,2]].reshape(2,2)

array([[86, 70],
       [96, 48]])

In [15]:
data2

array([[86, 73, 70],
       [54, 26, 27],
       [96, 70, 48]])

In [17]:
#54,26,73,96
data2[[1, 1, 0, 2],[0, 1, 1, 0]]

array([54, 26, 73, 96])