In [1]:
import numpy as np

In [2]:
data1 = np.random.randint(1,200,9)

In [3]:
data1

array([111,  33, 132, 110,  95,  33, 112, 120, 199])

In [4]:
data1[data1 == 30]

array([], dtype=int32)

In [5]:
data1[data1 > 100]

array([111, 132, 110, 112, 120, 199])

In [11]:
# Logical Operations
# and ---- &
# or ----- |
# not ---- !
data1[ (data1 > 100) & (data1 < 150) ]

array([129, 147])