In [1]:
import numpy as np

In [2]:
data1 = np.random.randint(1,200,9)

In [3]:
data1

array([ 73, 139, 121, 137,  64,  53, 155,  64, 186])

In [4]:
np.sqrt(data1)

array([ 8.54400375, 11.78982612, 11.        , 11.70469991,  8.        ,
        7.28010989, 12.4498996 ,  8.        , 13.6381817 ])

In [5]:
np.sin(data1)

array([-0.67677196,  0.69608013,  0.99881522, -0.94251445,  0.92002604,
        0.39592515, -0.87331198,  0.92002604, -0.60202394])

In [6]:
np.cos(data1)

array([-0.73619272,  0.7179641 , -0.04866361,  0.33416538,  0.39185723,
       -0.91828279, -0.48716135,  0.39185723, -0.79847804])

In [7]:
np.exp(data1)

array([5.05239363e+31, 2.32773204e+60, 3.54513118e+52, 3.15024275e+59,
       6.23514908e+27, 1.04137594e+23, 2.06844842e+67, 6.23514908e+27,
       6.00860471e+80])

In [8]:
np.exp(np.array([0]))

array([1.])

In [9]:
np.log(data1)

array([4.29045944, 4.93447393, 4.79579055, 4.91998093, 4.15888308,
       3.97029191, 5.04342512, 4.15888308, 5.22574667])